[project]
name = "my_redenomination_lib"
version = "0.1.0"
description = "A Python library for currency redenomination"
authors = [{name="Faiz Qowy", email="faizislamicqowy@gmail.com"}]
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["pandas", "numpy"]  # optional